export const phraseBank = [
  // Geral
  { topic:'Geral', en:"I'm almost there.", pt:'Estou quase chegando.', pro:'áim ólmoust dér' },
  { topic:'Geral', en:'Give me a minute.', pt:'Me dá um minuto.', pro:'guív mi a mínit' },
  { topic:'Geral', en:"I'll let you know.", pt:'Eu te aviso.', pro:'áil létchu nou' },
  { topic:'Geral', en:'Take your time.', pt:'Sem pressa.', pro:'têik iór táim' },
  { topic:'Geral', en:'Hang on a second.', pt:'Espera um segundo.', pro:'réng ón a sékand' },
  { topic:'Geral', en:"I didn't catch that.", pt:'Não entendi o que você disse.', pro:'ai dídant kétch dét' },
  { topic:'Geral', en:"It's worth a try.", pt:'Vale a pena tentar.', pro:'its uârth a trái' },
  { topic:'Geral', en:"I'll think about it.", pt:'Vou pensar sobre isso.', pro:'áil thínk abáut it' },
  { topic:'Geral', en:"I'm running late.", pt:'Estou atrasado.', pro:'áim râning lêit' },
  { topic:'Geral', en:"It's not a big deal.", pt:'Não é nada demais.', pro:'its nát a big díl' },
  { topic:'Geral', en:'What do you think?', pt:'O que você acha?', pro:'uât du iu thínk' },
  { topic:'Geral', en:"I'll take care of it.", pt:'Eu vou cuidar disso.', pro:'áil têik kér âv it' },
  { topic:'Geral', en:'Can you give me a hand?', pt:'Você pode me dar uma ajuda?', pro:'kén iu guív mi a rénd' },
  { topic:'Geral', en:"I'm getting ready.", pt:'Estou me arrumando.', pro:'áim gué-rin rédi' },
  { topic:'Geral', en:'It depends.', pt:'Depende.', pro:'it dipéndz' },
  { topic:'Geral', en:"That's a good idea.", pt:'Essa é uma boa ideia.', pro:'déts a gúd aidía' },
  { topic:'Geral', en:'Could you say that again?', pt:'Você poderia repetir?', pro:'cúdju sêi dét aguén' },
  { topic:'Geral', en:"I'm not sure.", pt:'Eu não tenho certeza.', pro:'áim nát shúr' },
  { topic:'Geral', en:'Sounds good to me.', pt:'Por mim, está ótimo.', pro:'sáundz gúd tchu mí' },
  { topic:'Geral', en:"I'll be there soon.", pt:'Estarei aí em breve.', pro:'áil bi dér sún' },
  { topic:'Geral', en:'What happened?', pt:'O que aconteceu?', pro:'uât ré-pand' },
  { topic:'Geral', en:"I'm just looking.", pt:'Estou só olhando.', pro:'áim djâst lúkin' },
  { topic:'Geral', en:'Do you need any help?', pt:'Você precisa de ajuda?', pro:'du iu níd éni rélp' },
  { topic:'Geral', en:"I'll call you later.", pt:'Eu te ligo mais tarde.', pro:'áil cól iu lêi-rer' },
  { topic:'Geral', en:"Don't worry about it.", pt:'Não se preocupe com isso.', pro:'dount uâri abáut it' },
  { topic:'Geral', en:'What are you doing?', pt:'O que você está fazendo?', pro:'uâ-rar iu dúin' },
  { topic:'Geral', en:'Are you serious?', pt:'Você está falando sério?', pro:'ar iu síriãs' },
  { topic:'Geral', en:"I'm just kidding.", pt:'Estou só brincando.', pro:'áim djâst kídin' },
  { topic:'Geral', en:'That makes sense.', pt:'Isso faz sentido.', pro:'dét mêiks sénss' },
  { topic:'Geral', en:"It's up to you.", pt:'Você que decide.', pro:'its âp tchu iu' },
  { topic:'Geral', en:'I have no idea.', pt:'Não faço ideia.', pro:'ai rév nou aidía' },
  { topic:'Geral', en:'What do you mean?', pt:'O que você quer dizer?', pro:'uât du iu mín' },
  { topic:'Geral', en:"I'll be right back.", pt:'Já volto.', pro:'áil bi ráit bék' },
  { topic:'Geral', en:'Give me a second.', pt:'Me dá um segundo.', pro:'guív mi a sékand' },
  { topic:'Geral', en:'No problem.', pt:'Sem problema.', pro:'nou próblem' },
  { topic:'Geral', en:'That works for me.', pt:'Por mim, está bom.', pro:'dét uârks for mí' },
  { topic:'Geral', en:'Let me check.', pt:'Deixa eu verificar.', pro:'lét mi tchék' },
  { topic:'Geral', en:"I'm on my way.", pt:'Estou a caminho.', pro:'áim ón mai uêi' },
  { topic:'Geral', en:'Maybe later.', pt:'Talvez mais tarde.', pro:'mêibi lêi-rer' },
  { topic:'Geral', en:'I totally agree.', pt:'Concordo totalmente.', pro:'ai tôurali agrí' },

  // Trabalho
  { topic:'Trabalho', en:'Can we talk for a minute?', pt:'Podemos conversar um minuto?', pro:'kén ui tók for a mínit' },
  { topic:'Trabalho', en:"I'll send you the file.", pt:'Vou te enviar o arquivo.', pro:'áil sénd iu da fáil' },
  { topic:'Trabalho', en:"I'm working on it.", pt:'Estou trabalhando nisso.', pro:'áim uârkin ón it' },
  { topic:'Trabalho', en:'When is the deadline?', pt:'Qual é o prazo?', pro:'uén iz da dédláin' },
  { topic:'Trabalho', en:'Can you check this?', pt:'Você pode verificar isso?', pro:'kén iu tchék dis' },
  { topic:'Trabalho', en:"I'll get back to you.", pt:'Eu te retorno.', pro:'áil guét bék tchu iu' },
  { topic:'Trabalho', en:'Are we still on for today?', pt:'Ainda está de pé para hoje?', pro:'ar ui stíl ón for tudêi' },
  { topic:'Trabalho', en:'I need more time.', pt:'Preciso de mais tempo.', pro:'ai níd mór táim' },
  { topic:'Trabalho', en:'The meeting was canceled.', pt:'A reunião foi cancelada.', pro:'da mí-rin uaz kénsald' },
  { topic:'Trabalho', en:"I'm available after lunch.", pt:'Estou disponível depois do almoço.', pro:'áim avêilabol áfter lântch' },
  { topic:'Trabalho', en:'Could you email me the details?', pt:'Pode me enviar os detalhes por e-mail?', pro:'cúdju ímeil mi da dítêils' },
  { topic:'Trabalho', en:"Let's keep it simple.", pt:'Vamos manter simples.', pro:'léts kíp it símpol' },
  { topic:'Trabalho', en:'I have a quick question.', pt:'Tenho uma pergunta rápida.', pro:'ai rév a kuík kuéstchan' },
  { topic:'Trabalho', en:'We need to fix this.', pt:'Precisamos corrigir isso.', pro:'ui níd tchu fíks dis' },
  { topic:'Trabalho', en:"I'll finish it today.", pt:'Vou terminar isso hoje.', pro:'áil fínish it tudêi' },
  { topic:'Trabalho', en:'Can we move the meeting?', pt:'Podemos remarcar a reunião?', pro:'kén ui múv da mí-rin' },
  { topic:'Trabalho', en:'Please keep me updated.', pt:'Por favor, me mantenha atualizado.', pro:'plíz kíp mi apdêi-rid' },
  { topic:'Trabalho', en:'I agree with the plan.', pt:'Concordo com o plano.', pro:'ai agrí uíth da plén' },
  { topic:'Trabalho', en:'What should we do next?', pt:'O que devemos fazer agora?', pro:'uât shud ui dú nékst' },
  { topic:'Trabalho', en:'Thanks for the update.', pt:'Obrigado pela atualização.', pro:'thénks for di apdêit' },

  // Viagem
  { topic:'Viagem', en:'Where is the bathroom?', pt:'Onde fica o banheiro?', pro:'uér iz da béthrum' },
  { topic:'Viagem', en:'How much is the ticket?', pt:'Quanto custa a passagem?', pro:'ráu mâtch iz da tíkit' },
  { topic:'Viagem', en:'What time does it leave?', pt:'Que horas sai?', pro:'uât táim dâz it lív' },
  { topic:'Viagem', en:'Is this seat taken?', pt:'Este assento está ocupado?', pro:'iz dis sít têikan' },
  { topic:'Viagem', en:'Where can I get a taxi?', pt:'Onde posso pegar um táxi?', pro:'uér kén ai guét a téksi' },
  { topic:'Viagem', en:"I'm here on vacation.", pt:'Estou aqui de férias.', pro:'áim rír ón vêikêishan' },
  { topic:'Viagem', en:'Can you show me on the map?', pt:'Pode me mostrar no mapa?', pro:'kén iu shou mi ón da mép' },
  { topic:'Viagem', en:'How far is it from here?', pt:'Fica a que distância daqui?', pro:'ráu far iz it fram rír' },
  { topic:'Viagem', en:'Do I need a reservation?', pt:'Preciso fazer reserva?', pro:'du ai níd a rézervêishan' },
  { topic:'Viagem', en:'I have a reservation.', pt:'Eu tenho uma reserva.', pro:'ai rév a rézervêishan' },
  { topic:'Viagem', en:'Could you take a picture of us?', pt:'Pode tirar uma foto nossa?', pro:'cúdju têik a píktcher âv âs' },
  { topic:'Viagem', en:"I'm looking for this address.", pt:'Estou procurando este endereço.', pro:'áim lúkin for dis adréss' },
  { topic:'Viagem', en:'Which gate is it?', pt:'Qual é o portão?', pro:'uítch guêit iz it' },
  { topic:'Viagem', en:'Is breakfast included?', pt:'O café da manhã está incluído?', pro:'iz brékfast inclúdid' },
  { topic:'Viagem', en:'Can I leave my bags here?', pt:'Posso deixar minhas malas aqui?', pro:'kén ai lív mai béguiz rír' },
  { topic:'Viagem', en:'Where do I check in?', pt:'Onde faço o check-in?', pro:'uér du ai tchék in' },
  { topic:'Viagem', en:'My flight is delayed.', pt:'Meu voo está atrasado.', pro:'mai fláit iz dilêid' },
  { topic:'Viagem', en:'I missed my flight.', pt:'Perdi meu voo.', pro:'ai míst mai fláit' },
  { topic:'Viagem', en:'Can I pay by card?', pt:'Posso pagar com cartão?', pro:'kén ai pêi bai kárd' },
  { topic:'Viagem', en:'Do you speak English?', pt:'Você fala inglês?', pro:'du iu spík ínglish' },

  // Relacionamento
  { topic:'Relacionamento', en:'I miss you.', pt:'Estou com saudade de você.', pro:'ai míss iu' },
  { topic:'Relacionamento', en:'Are you okay?', pt:'Você está bem?', pro:'ar iu oukêi' },
  { topic:'Relacionamento', en:"I'm here for you.", pt:'Estou aqui por você.', pro:'áim rír for iu' },
  { topic:'Relacionamento', en:"Let's talk about it.", pt:'Vamos conversar sobre isso.', pro:'léts tók abáut it' },
  { topic:'Relacionamento', en:'I understand how you feel.', pt:'Eu entendo como você se sente.', pro:'ai andersténd ráu iu fíl' },
  { topic:'Relacionamento', en:'I really appreciate you.', pt:'Eu valorizo muito você.', pro:'ai ríli apríshiêit iu' },
  { topic:'Relacionamento', en:'You make me happy.', pt:'Você me faz feliz.', pro:'iu mêik mi répi' },
  { topic:'Relacionamento', en:'Can I call you?', pt:'Posso te ligar?', pro:'kén ai cól iu' },
  { topic:'Relacionamento', en:'I need some space.', pt:'Preciso de um pouco de espaço.', pro:'ai níd sâm spêis' },
  { topic:'Relacionamento', en:"I'm proud of you.", pt:'Tenho orgulho de você.', pro:'áim práud âv iu' },
  { topic:'Relacionamento', en:'What are you thinking about?', pt:'No que você está pensando?', pro:'uât ar iu thínkin abáut' },
  { topic:'Relacionamento', en:'I trust you.', pt:'Eu confio em você.', pro:'ai trâst iu' },
  { topic:'Relacionamento', en:"I'm sorry about that.", pt:'Sinto muito por isso.', pro:'áim sóri abáut dét' },
  { topic:'Relacionamento', en:'Can we start over?', pt:'Podemos recomeçar?', pro:'kén ui stárt ôuver' },
  { topic:'Relacionamento', en:'I had a great time.', pt:'Eu me diverti muito.', pro:'ai réd a grêit táim' },
  { topic:'Relacionamento', en:'You can count on me.', pt:'Você pode contar comigo.', pro:'iu kén káunt ón mí' },
  { topic:'Relacionamento', en:'I was worried about you.', pt:'Eu estava preocupado com você.', pro:'ai uaz uârid abáut iu' },
  { topic:'Relacionamento', en:'Tell me what happened.', pt:'Me conta o que aconteceu.', pro:'tél mi uât ré-pand' },
  { topic:'Relacionamento', en:'I need to be honest with you.', pt:'Preciso ser sincero com você.', pro:'ai níd tchu bi ónest uíth iu' },
  { topic:'Relacionamento', en:"Everything's going to be okay.", pt:'Vai ficar tudo bem.', pro:'évri-thíngz gôuin tchu bi oukêi' },

  // Restaurante
  { topic:'Restaurante', en:'Can I see the menu?', pt:'Posso ver o cardápio?', pro:'kén ai sí da méniu' },
  { topic:'Restaurante', en:"I'd like some water, please.", pt:'Eu gostaria de água, por favor.', pro:'aid láik sâm uórer plíz' },
  { topic:'Restaurante', en:'What do you recommend?', pt:'O que você recomenda?', pro:'uât du iu rékaménd' },
  { topic:'Restaurante', en:"I'll have this one.", pt:'Vou querer este.', pro:'áil rév dis uân' },
  { topic:'Restaurante', en:'Can we get the check, please?', pt:'Pode trazer a conta, por favor?', pro:'kén ui guét da tchék plíz' },
  { topic:'Restaurante', en:'Is this spicy?', pt:'Isso é apimentado?', pro:'iz dis spáisi' },
  { topic:'Restaurante', en:"I'm allergic to peanuts.", pt:'Sou alérgico a amendoim.', pro:'áim alêrdjik tchu pínâts' },
  { topic:'Restaurante', en:'Can I get this without onions?', pt:'Pode ser sem cebola?', pro:'kén ai guét dis uitháut ânions' },
  { topic:'Restaurante', en:'Do you have any vegetarian options?', pt:'Vocês têm opções vegetarianas?', pro:'du iu rév éni vedjitérian ópshans' },
  { topic:'Restaurante', en:'Could I have another one?', pt:'Pode me trazer outro?', pro:'cud ai rév anâder uân' },
  { topic:'Restaurante', en:'This is delicious.', pt:'Isso está delicioso.', pro:'dis iz dilíshas' },
  { topic:'Restaurante', en:'Is service included?', pt:'O serviço está incluído?', pro:'iz sârvis inclúdid' },
  { topic:'Restaurante', en:'A table for two, please.', pt:'Uma mesa para dois, por favor.', pro:'a têibol for tú plíz' },
  { topic:'Restaurante', en:'Can I order to go?', pt:'Posso pedir para viagem?', pro:'kén ai órder tchu gou' },
  { topic:'Restaurante', en:'What comes with this?', pt:'O que acompanha isso?', pro:'uât câms uíth dis' },
  { topic:'Restaurante', en:'Could we have more napkins?', pt:'Pode trazer mais guardanapos?', pro:'cud ui rév mór népkins' },
  { topic:'Restaurante', en:'I asked for no ice.', pt:'Eu pedi sem gelo.', pro:'ai éskt for nou áis' },
  { topic:'Restaurante', en:'Can you make it less spicy?', pt:'Pode fazer menos apimentado?', pro:'kén iu mêik it lés spáisi' },
  { topic:'Restaurante', en:'Everything was great.', pt:'Estava tudo ótimo.', pro:'évri-thíng uaz grêit' },
  { topic:'Restaurante', en:'Can we split the bill?', pt:'Podemos dividir a conta?', pro:'kén ui splít da bíl' },

  // Compras
  { topic:'Compras', en:'How much is this?', pt:'Quanto custa isso?', pro:'ráu mâtch iz dis' },
  { topic:'Compras', en:'Do you have this in a different size?', pt:'Tem isso em outro tamanho?', pro:'du iu rév dis in a dífrant sáiz' },
  { topic:'Compras', en:'Can I try this on?', pt:'Posso experimentar isso?', pro:'kén ai trái dis ón' },
  { topic:'Compras', en:'Where is the fitting room?', pt:'Onde fica o provador?', pro:'uér iz da fí-rin rúm' },
  { topic:'Compras', en:"I'm just browsing.", pt:'Estou só dando uma olhada.', pro:'áim djâst bráuzin' },
  { topic:'Compras', en:'Do you have a smaller one?', pt:'Tem um menor?', pro:'du iu rév a smóler uân' },
  { topic:'Compras', en:'Do you have a larger one?', pt:'Tem um maior?', pro:'du iu rév a lárdjer uân' },
  { topic:'Compras', en:'Is this on sale?', pt:'Isso está em promoção?', pro:'iz dis ón sêil' },
  { topic:'Compras', en:'Can I pay in cash?', pt:'Posso pagar em dinheiro?', pro:'kén ai pêi in késh' },
  { topic:'Compras', en:'Do you accept credit cards?', pt:'Vocês aceitam cartão de crédito?', pro:'du iu aksépt crédit kárdz' },
  { topic:'Compras', en:'Can I get a receipt?', pt:'Posso pegar o recibo?', pro:'kén ai guét a risít' },
  { topic:'Compras', en:'Can I return this?', pt:'Posso devolver isso?', pro:'kén ai ritârn dis' },
  { topic:'Compras', en:'Does this come in black?', pt:'Tem isso na cor preta?', pro:'dâz dis câme in blék' },
  { topic:'Compras', en:"I'll take it.", pt:'Vou levar.', pro:'áil têik it' },
  { topic:'Compras', en:"That's too expensive.", pt:'Isso está caro demais.', pro:'déts tú ikspénsiv' },
  { topic:'Compras', en:'Is there a discount?', pt:'Tem desconto?', pro:'iz dér a dískaunt' },
  { topic:'Compras', en:'Where can I find this?', pt:'Onde posso encontrar isso?', pro:'uér kén ai fáind dis' },
  { topic:'Compras', en:'Can you gift-wrap this?', pt:'Pode embrulhar para presente?', pro:'kén iu guíft-rép dis' },
  { topic:'Compras', en:'Do you have another color?', pt:'Tem outra cor?', pro:'du iu rév anâder câler' },
  { topic:'Compras', en:'Can you hold this for me?', pt:'Pode guardar isso para mim?', pro:'kén iu rôuld dis for mí' }
]
